---


# Adicionando o reposit처rio do FortiClient

- name: "Adicionando reposit처rio do FortiClient vers찾o {{ forticlient_version }}"
  get_url:
    url: "{{ fedora_forticlient_repo_url }}"
    dest: "{{fedora_forticlient_repo_dest }}"
  become: true
  tags:
    - forticlient
    - repo


# Instalando o FortiClient

- name: "Instalando o pacote FortiClient vers찾o {{ forticlient_version }}"
  dnf:
    name: "{{ forticlient_package }}"
    state: present
  become: true
  tags:
    - forticlient